### ISSUE TITLE
TestK8sGatewayNoValidation/VirtualHostOptions/TestMultipleVirtualHostOptionsManualSetup

### ISSUE THREAD

**Issue by ashishb-solo** [k8sgateway/k8sgateway#10310] opened 2024-11-11 16:03 UTC
### Which tests failed?

Failed in this run: https://github.com/solo-io/gloo/actions/runs/11749515320/job/32735946327

Revelant context:

```
2024-11-08T23:10:45.6168422Z }=== NAME  TestK8sGatewayNoValidation
2024-11-08T23:10:45.6168557Z     status.go:35: 
2024-11-08T23:10:45.6168716Z         Timed out after 20.000s.
2024-11-08T23:10:45.6169503Z         The function passed to Eventually failed at /home/runner/work/gloo/gloo/test/kubernetes/testutils/assertions/status.go:34 with:
2024-11-08T23:10:45.6169964Z         have matcher for namespace k8s-gw-test-no-validation which is not found
2024-11-08T23:10:45.6170272Z virtualhostoption.gateway.solo.io "remove-content-length" deleted
2024-11-08T23:10:45.6170559Z virtualhostoption.gateway.solo.io "remove-content-type" deleted
2024-11-08T23:10:45.6170969Z === NAME  TestK8sGatewayNoValidation/VirtualHostOptions/TestMultipleVirtualHostOptionsManualSetup
2024-11-08T23:10:45.6171637Z     testing.go:1577: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
2024-11-08T23:10:45.6171826Z gateway.gateway.networking.k8s.io "gw" deleted
2024-11-08T23:10:45.6172098Z httproute.gateway.networking.k8s.io "example-route" deleted
2024-11-08T23:10:45.6172239Z service "example-svc" deleted
2024-11-08T23:10:45.6172345Z pod "nginx" deleted
2024-11-08T23:10:45.6172454Z namespace "curl" deleted
2024-11-08T23:10:45.6172558Z pod "curl" deleted
2024-11-08T23:10:45.6172746Z === NAME  TestK8sGatewayNoValidation/VirtualHostOptions
2024-11-08T23:10:45.6173265Z     testing.go:1577: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
2024-11-08T23:10:45.6174088Z [31m[1m"[0m[31mFri, 08 Nov 2024 23:10:27 UTC: /home/runner/work/gloo/gloo/test/kubernetes/testutils/helper/install.go:452[0m[31m[1m"[0m	uninstalling gloo...
2024-11-08T23:10:45.6174220Z   Uninstalling Gloo Gateway...
2024-11-08T23:10:45.6174603Z   Removing Gloo system components from namespace k8s-gw-test-no-validation...
2024-11-08T23:10:45.6174719Z   Removing Gloo CRDs...
2024-11-08T23:10:45.6174973Z   Removing namespace k8s-gw-test-no-validation... Done.
2024-11-08T23:10:45.6174980Z 
2024-11-08T23:10:45.6175116Z   Gloo was successfully uninstalled.
2024-11-08T23:10:45.6175320Z --- FAIL: TestK8sGatewayNoValidation (153.14s)
2024-11-08T23:10:45.6175661Z     --- FAIL: TestK8sGatewayNoValidation/VirtualHostOptions (77.98s)
2024-11-08T23:10:45.6176318Z         --- PASS: TestK8sGatewayNoValidation/VirtualHostOptions/TestConfigureInvalidVirtualHostOptions (2.34s)
2024-11-08T23:10:45.6176919Z         --- PASS: TestK8sGatewayNoValidation/VirtualHostOptions/TestConfigureVirtualHostOptions (2.39s)
2024-11-08T23:10:45.6177722Z         --- PASS: TestK8sGatewayNoValidation/VirtualHostOptions/TestConfigureVirtualHostOptionsWithSectionNameManualSetup (4.83s)
2024-11-08T23:10:45.6178408Z         --- FAIL: TestK8sGatewayNoValidation/VirtualHostOptions/TestMultipleVirtualHostOptionsManualSetup (22.42s)
2024-11-08T23:10:45.6178497Z FAIL
2024-11-08T23:10:45.6178777Z FAIL	github.com/solo-io/gloo/test/kubernetes/e2e/tests	773.613s
2024-11-08T23:10:45.6178857Z FAIL
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206681874205238/1208751376778788) by [Unito](https://www.unito.io)

**Comment by ashishb-solo** [comment] 2024-11-11 16:03
Failed a second time in this run: https://github.com/solo-io/gloo/actions/runs/11750674300/job/32739359225

**Comment by ashishb-solo** [comment] 2024-11-12 14:27
hit this a second day in a row: https://github.com/solo-io/gloo/actions/runs/11791050661/job/32842485859

**Comment by sheidkamp** [comment] 2024-11-15 15:01
1.18 PR

https://github.com/solo-io/gloo/actions/runs/11848658964/job/33020586917?pr=10355

**Comment by sheidkamp** [comment] 2024-11-15 19:18
1.18 PR: https://github.com/solo-io/gloo/actions/runs/11861579084/job/33059209923?pr=10355

**Comment by sam-heilbron** [comment] 2024-11-27 17:06
@ryanrolds It sounds like this flake hasn't happened in a while, and you pushed a PR that improves these tests. Should we close this issue?

**Comment by ryanrolds** [comment] 2024-11-27 17:52
Yes. I would close it it but I can't.

**Comment by sam-heilbron** [comment] 2024-11-28 03:17
Confirmed with @ryanrolds offline, he does not have permissions to close the issue, and so I am doing it on his behalf.

@ilrudie Is this a known limitation for non-maintainers?

**Closed by sam-heilbron** 2024-11-28 03:17 UTC
Labels: Type: Bug, Type: CI Test Flake, Prioritized

**Comment by ilrudie** [comment] 2024-11-28 03:20
It's almost certainly a limitation on folks who are not yet org members since that is basically anyone at all with a github login.
